# Generated by Django 4.2.7 on 2023-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BSIC_INFO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=20, verbose_name="ip")),
                ("hostname", models.CharField(max_length=20, verbose_name="主机名")),
                ("assset_desc", models.CharField(max_length=20, verbose_name="资产描述")),
                ("os_type", models.CharField(max_length=20, verbose_name="操作系统")),
            ],
            options={
                "verbose_name": "BSIC信息",
                "verbose_name_plural": "BSIC信息",
                "db_table": "bsic_info",
            },
        ),
    ]
