# Generated by Django 4.2.7 on 2023-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bsic_info",
            name="name",
            field=models.CharField(
                default="基础信息表", max_length=20, verbose_name="基础信息表"
            ),
        ),
    ]
