# Generated by Django 4.2.7 on 2024-01-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0002_bsic_info_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bsic_info",
            name="cpu_cores",
            field=models.CharField(default="", max_length=20, verbose_name="cpu核数"),
        ),
        migrations.AddField(
            model_name="bsic_info",
            name="sys_password",
            field=models.CharField(default="", max_length=255, verbose_name="密码"),
        ),
        migrations.AddField(
            model_name="bsic_info",
            name="sys_user",
            field=models.CharField(default="", max_length=100, verbose_name="用户名"),
        ),
    ]
