# Generated by Django 4.2.7 on 2024-03-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0003_bsic_info_cpu_cores_bsic_info_sys_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bsic_info",
            name="sys_password",
            field=models.CharField(default="", max_length=255, verbose_name="系统密码"),
        ),
        migrations.AlterField(
            model_name="bsic_info",
            name="sys_user",
            field=models.CharField(default="", max_length=100, verbose_name="系统用户"),
        ),
    ]
